# This Makefile is generated by omake: https://github.com/ouonline/omake.git

CXX := g++

ifeq ($(debug), y)
	CXXFLAGS += -g
else
	CXXFLAGS += -O2 -DNDEBUG
endif

AR := ar

TARGET := libthreadpool_shared.so libthreadpool_static.a

.PHONY: all clean

all: $(TARGET)

threadpool.cpp.omake_dep_0.o: threadpool.cpp
	$(CXX) $(CXXFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

threadpool_shared_OBJS := threadpool.cpp.omake_dep_0.o

threadpool_shared_LIBS := -lpthread

libthreadpool_shared.so: $(threadpool_shared_OBJS)
	$(CXX) $(CXXFLAGS) -shared -o $@ $^ $(threadpool_shared_LIBS)

threadpool_static_OBJS := threadpool.cpp.omake_dep_0.o

libthreadpool_static.a: $(threadpool_static_OBJS)
	$(AR) rc $@ $^

clean:
	rm -f $(TARGET) $(threadpool_shared_OBJS) $(threadpool_static_OBJS)
