# This Makefile is generated by omake: https://github.com/ouonline/omake.git

AR := ar
CXX := g++

ifeq ($(debug), y)
	CXXFLAGS := -g
else
	CXXFLAGS := -O2 -DNDEBUG
endif
CXXFLAGS := $(CXXFLAGS) -Wall -Werror -Wextra -fPIC

TARGET := libthreadpool.a libthreadpool.so

.PHONY: all clean

all: $(TARGET)

threadpool_OBJS := threadpool.cpp.threadpool.o

threadpool_INCLUDE :=

threadpool_LIBS := -lpthread

threadpool.cpp.threadpool.o: threadpool.cpp
	$(CXX) $(CXXFLAGS) $(threadpool_INCLUDE) -c $< -o $@

libthreadpool.a: $(threadpool_OBJS)
	$(AR) rc $@ $^

libthreadpool.so: $(threadpool_OBJS)
	$(CXX) -shared -o $@ $^ $(threadpool_LIBS)

clean:
	rm -f $(TARGET) $(threadpool_OBJS)
