# This Makefile is generated by omake: https://github.com/ouonline/omake.git

CXX := g++

ifeq ($(debug), y)
	CXXFLAGS += -g
else
	CXXFLAGS += -O2 -DNDEBUG
endif

AR := ar

TARGET := libthreadkit_shared.so libthreadkit_static.a

.PHONY: all clean distclean

all: $(TARGET)

omake_dep_0.threadpool.cpp.o: threadpool.cpp
	$(CXX) $(CXXFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

threadkit_shared_OBJS := omake_dep_0.threadpool.cpp.o

threadkit_shared_LIBS := -lpthread

libthreadkit_shared.so: $(threadkit_shared_OBJS)
	$(CXX) $(CXXFLAGS) -fPIC -Wextra -Werror -Wall -shared -o $@ $^ $(threadkit_shared_LIBS)

threadkit_static_OBJS := omake_dep_0.threadpool.cpp.o

libthreadkit_static.a: $(threadkit_static_OBJS)
	$(AR) rc $@ $^

clean:
	rm -f $(TARGET) $(threadkit_shared_OBJS) $(threadkit_static_OBJS)

distclean:
	$(MAKE) clean
